fix: Comment out load_config job and its steps in docker-dev workflow

diff --git a/.github/workflows/docker-dev.yml b/.github/workflows/docker-dev.yml
--- a/.github/workflows/docker-dev.yml
+++ b/.github/workflows/docker-dev.yml
@@ -24,45 +24,45 @@ permissions:
   packages: write
 
 jobs:
-  load_config:
-    name: "Load Docker Configuration"
-    runs-on: ubuntu-latest
-    outputs:
-      components: ${{ steps.load_component.outputs.components }}
-      platforms: ${{ steps.load_component.outputs.platforms }}
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+  # load_config:
+  #   name: "Load Docker Configuration"
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     components: ${{ steps.load_component.outputs.components }}
+  #     platforms: ${{ steps.load_component.outputs.platforms }}
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
 
-      - name: Load Docker Configuration
-        id: load_component
-        shell: bash
-        run: |
-          verify=$(cat "$GITHUB_WORKSPACE/.github/docker-dev-config.json" | jq '
-            def verify_structure:
-              .components as $components
-              | .platforms as $platforms
-              | ($components | type == "array")
-              and (all($components[]; has("name") and has("file") and has("context")))
-              and ($platforms | type == "string");
-            verify_structure
-            | if . then true else false end
-          ')
-          if [ "${verify}" == "true" ]; then
-            echo "✅ $GITHUB_WORKSPACE/.github/docker-dev-config.json file is valid"
-            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-dev-config.json")
-            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-dev-config.json")
-          else
-            echo "❗ $GITHUB_WORKSPACE/.github/docker-dev-config.json file is invalid"
-            echo "❗ $GITHUB_WORKSPACE/.github/docker-dev-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-          echo "components=${components}" >> "$GITHUB_OUTPUT"
-          echo "platforms=${platforms}" >> "$GITHUB_OUTPUT"
+  #     - name: Load Docker Configuration
+  #       id: load_component
+  #       shell: bash
+  #       run: |
+  #         verify=$(cat "$GITHUB_WORKSPACE/.github/docker-dev-config.json" | jq '
+  #           def verify_structure:
+  #             .components as $components
+  #             | .platforms as $platforms
+  #             | ($components | type == "array")
+  #             and (all($components[]; has("name") and has("file") and has("context")))
+  #             and ($platforms | type == "string");
+  #           verify_structure
+  #           | if . then true else false end
+  #         ')
+  #         if [ "${verify}" == "true" ]; then
+  #           echo "✅ $GITHUB_WORKSPACE/.github/docker-dev-config.json file is valid"
+  #           components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-dev-config.json")
+  #           platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-dev-config.json")
+  #         else
+  #           echo "❗ $GITHUB_WORKSPACE/.github/docker-dev-config.json file is invalid"
+  #           echo "❗ $GITHUB_WORKSPACE/.github/docker-dev-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
+  #           exit 1
+  #         fi
+  #         echo "components=${components}" >> "$GITHUB_OUTPUT"
+  #         echo "platforms=${platforms}" >> "$GITHUB_OUTPUT"
 
   perform-version:
     runs-on: ubuntu-latest
-    needs: [load_config]
+    # needs: [load_config]
     outputs:
       metadata: "${{ steps.metadata.outputs.result }}"
       tags: "${{ steps.prepare_tags.outputs.tags }}"
