Update docker_dev.yml

diff --git a/.github/workflows/docker_dev.yml b/.github/workflows/docker_dev.yml
--- a/.github/workflows/docker_dev.yml
+++ b/.github/workflows/docker_dev.yml
@@ -4,7 +4,7 @@ on:
   pull_request:
     types: [opened, reopened, synchronize]
     branches:
-      - main
+    - main
   workflow_dispatch:
     inputs:
       tags:
@@ -25,33 +25,33 @@ jobs:
       component: ${{ steps.load_component.outputs.components }}
       platforms: ${{ steps.load_component.outputs.platforms }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Load Docker Configuration
-        id: load_component
-        run: |
-          verify=$(cat "$GITHUB_WORKSPACE/.github/dev-docker-config.json" | jq '
-          def verify_structure:
-          .components as $components
-          | .platforms as $platforms
-          | ($components | type == "array")
-          and (all($components[]; has("name") and has("file") and has("context")))
-          and ($platforms | type == "string");
-          verify_structure
-          | if . then true else false end
-          ')
-          if [ ${verify} == 'true' ]; then
-            echo "✅ $GITHUB_WORKSPACE/.github/dev-docker-config.json file is valid"
-            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/dev-docker-config.json")
-            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/dev-docker-config.json")
-          else
-            echo "❗ $GITHUB_WORKSPACE/.github/dev-docker-config.json file is invalid"
-            echo "❗ $GITHUB_WORKSPACE/.github/dev-docker-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-          echo "components=${components}" >> $GITHUB_OUTPUT
-          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
+    - name: Load Docker Configuration
+      id: load_component
+      run: |
+        verify=$(cat "$GITHUB_WORKSPACE/.github/dev-docker-config.json" | jq '
+        def verify_structure:
+        .components as $components
+        | .platforms as $platforms
+        | ($components | type == "array")
+        and (all($components[]; has("name") and has("file") and has("context")))
+        and ($platforms | type == "string");
+        verify_structure
+        | if . then true else false end
+        ')
+        if [ ${verify} == 'true' ]; then
+          echo "✅ $GITHUB_WORKSPACE/.github/dev-docker-config.json file is valid"
+          components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/dev-docker-config.json")
+          platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/dev-docker-config.json")
+        else
+          echo "❗ $GITHUB_WORKSPACE/.github/dev-docker-config.json file is invalid"
+          echo "❗ $GITHUB_WORKSPACE/.github/dev-docker-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+        echo "components=${components}" >> $GITHUB_OUTPUT
+        echo "platforms=${platforms}" >> $GITHUB_OUTPUT
 
   perform-version:
     runs-on: ubuntu-latest
@@ -59,31 +59,31 @@ jobs:
       metadata: "${{ steps.metadata.outputs.result }}"
       tags: "${{ steps.prepare_tags.outputs.tags }}"
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Create name
-        uses: netcracker/qubership-workflow-hub/actions/metadata-action@main
-        id: metadata
-        with:
-          configuration-path: .github/dev-metadata-config.yml
-          short-sha: 11
+    - name: Create name
+      uses: netcracker/qubership-workflow-hub/actions/metadata-action@main
+      id: metadata
+      with:
+        configuration-path: .github/dev-metadata-config.yml
+        short-sha: 11
 
-      - name: Echo metadata
-        run: echo "Metadata result ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
+    - name: Echo metadata
+      run: echo "Metadata result ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
 
-      - name: Prepare tags
-        id: prepare_tags
-        run: |
-          BASE_TAG="${{ steps.metadata.outputs.result }}"
-          EXTRA_TAG="${{ github.event.inputs.tags }}"
-          if [ -n "$EXTRA_TAG" ]; then
-            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
-          else
-            TAGS="${BASE_TAG}"
-          fi
-          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
-          echo "tags: ${TAGS}" >> $GITHUB_STEP_SUMMARY
+    - name: Prepare tags
+      id: prepare_tags
+      run: |
+        BASE_TAG="${{ steps.metadata.outputs.result }}"
+        EXTRA_TAG="${{ github.event.inputs.tags }}"
+        if [ -n "$EXTRA_TAG" ]; then
+          TAGS="${BASE_TAG}, ${EXTRA_TAG}"
+        else
+          TAGS="${BASE_TAG}"
+        fi
+        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
+        echo "tags: ${TAGS}" >> $GITHUB_STEP_SUMMARY
 
   docker-build:
     uses: nookyo/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
